# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Time-Normalize
version:      0.05
version_from: Normalize.pm
installdirs:  site
requires:
    Test::Simple:                  0.40

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
